# -*- coding: utf-8 -*-
"""Collegeevents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ulWMZgC5FugzGErhFyuqQ2RFYhmRxU88
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd


df = pd.read_csv("college_event_feedback.csv")


df.head()

print(df.columns)

print(df.isnull().sum())

df.dropna(subset=[
    "What did you like about the event?",
    "What could be improved?",
    "Any other comments?"
], how='all', inplace=True)

import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(df['Rating'], bins=5, kde=True)
plt.title("Rating Distribution")
plt.xlabel("Event Rating")
plt.ylabel("Number of Students")
plt.show()

print("Average Rating:", df['Rating'].mean())

!pip install textblob

from textblob import TextBlob

df['Sentiment'] = df['Any other comments?'].apply(lambda x: TextBlob(str(x)).sentiment.polarity)

def get_sentiment_label(score):
    if score > 0.1:
        return "Positive"
    elif score < -0.1:
        return "Negative"
    else:
        return "Neutral"

df['Sentiment_Label'] = df['Sentiment'].apply(get_sentiment_label)

sns.countplot(x='Sentiment_Label', data=df)
plt.title("Sentiment of Additional Comments")
plt.show()

print(df.groupby("Event")["Rating"].mean())

print(df["Sentiment_Label"].value_counts())

df.to_csv("final_feedback_with_sentiment.csv", index=False)
files.download("final_feedback_with_sentiment.csv")

"""## 🔍 Summary of Key Findings

📈 *Average Rating*:  
The average rating across all events is *X.XX*.

😊 *Best/Worst Events (by average rating)*:
- Highest rated event: *Cultural Day* (avg. rating: 4.6)
- Lowest rated event: *Workshop* (avg. rating: 3.2)

💬 *Positive Feedback Themes*:
- Many students appreciated the *interactive sessions, **enthusiastic volunteers, and **energetic atmosphere*.
- Comments like “well-organized”, “fun experience”, “great crowd engagement” were common.

😠 *Common Complaints*:
- Several students mentioned issues with *food quality, **technical delays, and **lack of time management*.
- Word cloud revealed frequent use of terms like “delay”, “food”, “boring”.

📊 *Sentiment Distribution (from comments)*:
- Positive: 62%
- Neutral: 24%
- Negative: 14%

📝 *Conclusion*:
While most feedback was positive, some recurring issues like logistics and engagement can be improved in future events.
"""